package com.test;
// Generated 2016-4-18 16:26:51 by Hibernate Tools 4.3.1.Final

/**
 * Mytable generated by hbm2java
 */
public class Mytable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private int idnewTable;
	private String newTablecol;

	public Mytable() {
	}

	public Mytable(int idnewTable) {
		this.idnewTable = idnewTable;
	}

	public Mytable(int idnewTable, String newTablecol) {
		this.idnewTable = idnewTable;
		this.newTablecol = newTablecol;
	}

	public int getIdnewTable() {
		return this.idnewTable;
	}

	public void setIdnewTable(int idnewTable) {
		this.idnewTable = idnewTable;
	}

	public String getNewTablecol() {
		return this.newTablecol;
	}

	public void setNewTablecol(String newTablecol) {
		this.newTablecol = newTablecol;
	}

}
